import React from 'react';

export default function PrivacyPolicy() {
  return (
    <div className="max-w-3xl mx-auto p-8 py-20 prose prose-slate">
      <h1>Политика конфиденциальности</h1>
      <p>Последнее обновление: {new Date().toLocaleDateString('ru-RU')}</p>
      
      <h2>1. Сбор данных</h2>
      <p>Мы собираем только те данные, которые необходимы для работы образовательной платформы: email, имя пользователя и результаты прохождения уроков.</p>

      <h2>2. Использование данных</h2>
      <p>Ваши данные используются исключительно для обеспечения связи между преподавателем и учеником, а также для автоматической проверки заданий.</p>

      <h2>3. Безопасность</h2>
      <p>Мы принимаем все необходимые технические меры для защиты ваших данных от несанкционированного доступа.</p>
      {/* Add your full legal text here generated by a lawyer or Legal generator for your specific country */}
    </div>
  );
}